name: Deploy Strapi to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-2
  ECR_REPO: 607700977843.dkr.ecr.us-east-2.amazonaws.com/strapi-app-ecr-dhan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::607700977843:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REPO:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Terraform variable
        run: |
          sed -i "s/default *= *\"latest\"/default = \"${{ env.IMAGE_TAG }}\"/" variables.tf

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
